name: Update dependencies
on:
  schedule:
    - cron: "0 0 * * 0"

  workflow_dispatch:
jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update dependencies
        uses: pdm-project/update-deps-action@v1
